const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{Play: 0},
	{esquerda: 0},
	{direita: 0},
	{Pulo: 0},
	{Toque: 0},
	{CAIXA: 0},
	{ENTRADA: 0},
	{PORTASAIDA: 0},
	{LIMITES: 0},
	{PARTICULACAIXA: 0},
	{PLATAFORMA: 0},
	{CHAVE: 0},
	{fundo: 0},
	{Senóide: 0},
	{inimigo: 0},
	{MORTEINIMIGO: 0},
	{FUNDOMENU: 0},
	{JOGAR: 0},
	{CHAVE2: 0},
	{Texto: 0},
	{TXTCHAVE: 0},
	{Sprite: 0},
	{TXTVIDAS: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Áudio: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{ESTADO: 0},
	{ACHOUCHAVE: 0},
	{vidas: 0},
	{CHAVES: 0}
];

self.InstanceType = {
	chao: class extends self.ITiledBackgroundInstance {},
	Play: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	Pulo: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	CAIXA: class extends self.ISpriteInstance {},
	ENTRADA: class extends self.ISpriteInstance {},
	PORTASAIDA: class extends self.ISpriteInstance {},
	LIMITES: class extends self.ISpriteInstance {},
	PARTICULACAIXA: class extends self.IParticlesInstance {},
	PLATAFORMA: class extends self.ITiledBackgroundInstance {},
	CHAVE: class extends self.ISpriteInstance {},
	fundo: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	MORTEINIMIGO: class extends self.IParticlesInstance {},
	FUNDOMENU: class extends self.ISpriteInstance {},
	JOGAR: class extends self.ISpriteInstance {},
	CHAVE2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	TXTCHAVE: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TXTVIDAS: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {}
}